///////////////////////////////////////////////////////////
//  Bueno.cs
//  Implementation of the Class Bueno
//  Generated by Enterprise Architect
//  Created on:      06-may.-2020 19:58:14
//  Original author: pier
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ejercicio63;
namespace ejercicio63 {
	public class Bueno : Tipo_Personaje {

		public Bueno(){

		}

	}//end Bueno

}//end namespace ejercicio63