///////////////////////////////////////////////////////////
//  Habilidad.cs
//  Implementation of the Class Habilidad
//  Generated by Enterprise Architect
//  Created on:      06-may.-2020 19:58:17
//  Original author: pier
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ejercicio63;
namespace ejercicio63 {
	public class Habilidad {

		private string descripcion;
		public ejercicio63.Personaje m_Personaje;

		public Habilidad(){

		}

	}//end Habilidad

}//end namespace ejercicio63