///////////////////////////////////////////////////////////
//  Heroe.cs
//  Implementation of the Class Heroe
//  Generated by Enterprise Architect
//  Created on:      06-may.-2020 19:59:18
//  Original author: pier
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ejercicio63;
namespace ejercicio63 {
	public class Heroe : Personaje {

		public Heroe(){

		}

	}//end Heroe

}//end namespace ejercicio63