///////////////////////////////////////////////////////////
//  Inteligente.cs
//  Implementation of the Class Inteligente
//  Generated by Enterprise Architect
//  Created on:      06-may.-2020 19:58:22
//  Original author: pier
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ejercicio63;
namespace ejercicio63 {
	public class Inteligente : Tipo_Personaje {

		public Inteligente(){

		}

	}//end Inteligente

}//end namespace ejercicio63