///////////////////////////////////////////////////////////
//  Malo.cs
//  Implementation of the Class Malo
//  Generated by Enterprise Architect
//  Created on:      06-may.-2020 19:58:26
//  Original author: pier
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ejercicio63;
namespace ejercicio63 {
	public class Malo : Tipo_Personaje {

		public Malo(){

		}

	}//end Malo

}//end namespace ejercicio63