///////////////////////////////////////////////////////////
//  Monstruo.cs
//  Implementation of the Class Monstruo
//  Generated by Enterprise Architect
//  Created on:      06-may.-2020 19:58:29
//  Original author: pier
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ejercicio63;
namespace ejercicio63 {
	public class Monstruo : Personaje {

		public Monstruo(){

		}

	}//end Monstruo

}//end namespace ejercicio63