///////////////////////////////////////////////////////////
//  Personaje.cs
//  Implementation of the Class Personaje
//  Generated by Enterprise Architect
//  Created on:      06-may.-2020 19:58:43
//  Original author: pier
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ejercicio63;
namespace ejercicio63 {
	public abstract class Personaje {

		private decimal altura;
		private Habilidad habilidades;
		private string imagen;
		private int inteligencia;
		private string nombre;
		private decimal peso;
		private Tipo_Personaje tipoPersonaje;
		public ejercicio63.Usuario m_Usuario;

		public Personaje(){

		}

		/// 
		/// <param name="nombre"></param>
		/// <param name="imagen"></param>
		/// <param name="inteligencia"></param>
		/// <param name="altura"></param>
		/// <param name="peso"></param>
		public Personaje(string nombre, string imagen, int inteligencia, decimal altura, decimal peso){

		}

		/// 
		/// <param name="habilidad"></param>
		public void agregarHabilidad(Habilidad habilidad){
			this.habilidad = habilidad;
		}

	}//end Personaje

}//end namespace ejercicio63