///////////////////////////////////////////////////////////
//  Principe.cs
//  Implementation of the Class Principe
//  Generated by Enterprise Architect
//  Created on:      06-may.-2020 19:58:54
//  Original author: pier
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ejercicio63;
namespace ejercicio63 {
	public class Principe : Personaje {

		public Principe(){

		}

	}//end Principe

}//end namespace ejercicio63