///////////////////////////////////////////////////////////
//  Tipo_Personaje.cs
//  Implementation of the Class Tipo_Personaje
//  Generated by Enterprise Architect
//  Created on:      06-may.-2020 19:58:57
//  Original author: pier
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ejercicio63;
namespace ejercicio63 {
	public class Tipo_Personaje {

		public ejercicio63.Personaje m_Personaje;

		public Tipo_Personaje(){

		}

	}//end Tipo_Personaje

}//end namespace ejercicio63