///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Villano
//  Generated by Enterprise Architect
//  Created on:      06-may.-2020 19:57:58
//  Original author: pier
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ejercicio63;
namespace ejercicio63 {
	public class Usuario {

		private Personaje listPersonaje;

		public Usuario(){

		}

		/// 
		/// <param name="Personaje"></param>
		public void agregarPersonaje(Personaje Personaje){
			this.listPersonaje.Add(Personaje);
		}

	}//end Usuario//end Villano

}//end namespace ejercicio63