///////////////////////////////////////////////////////////
//  Villano.cs
//  Implementation of the Class Villano
//  Generated by Enterprise Architect
//  Created on:      06-may.-2020 19:59:29
//  Original author: pier
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ejercicio63;
namespace ejercicio63 {
	public class Villano : Personaje {

		public Villano(){

		}

	}//end Villano

}//end namespace ejercicio63